{
 "title": "Django API - Visão Geral",
 "tags": [
  "django",
  "api",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requisições por Minuto",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_total_by_view_transport_method_total[1m])) * 60"
    }
   ]
  },
  {
   "title": "Requisições por Endpoint (req/min)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (view) (rate(django_http_requests_total_by_view_transport_method_total[5m])) * 60",
     "legendFormat": "{{view}}"
    }
   ]
  },
  {
   "title": "Latência Média",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum[5m]) / rate(django_http_requests_latency_seconds_by_view_method_count[5m])",
     "legendFormat": "Latência Média"
    }
   ]
  }
 ]
}