# Generated by Django 4.2.25 on 2026-01-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vigilant", "0001_initial"),
        ("branch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="branch.branch",
                    ),
                ),
                (
                    "vigilant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="vigilant.vigilant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico",
                "verbose_name_plural": "Históricos",
                "ordering": ["-created_at"],
            },
        ),
    ]
